export const SET_COMMENTS = `SET_COMMENTS`;
export const START_REVIEW_SENDING = `START_REVIEW_SENDING`;
export const FINISH_REVIEW_SENDING = `FINISH_REVIEW_SENDING`;
export const SET_NEARBY = `SET_NEARBY`;
export const SET_CHOOSED = `SET_CHOOSED`;
