export const SET_COMMENTS = `SET_COMMENTS`;
export const START_REVIEW_SENDING = `START_REVIEW_SENDING`;
export const FINISH_REVIEW_SENDING = `FINISH_REVIEW_SENDING`;
export const SET_NEARBY = `SET_NEARBY`;
export const SET_CHOOSED = `SET_CHOOSED`;
export const SET_FORM_ERROR = `SET_FORM_ERROR`;
export const CLEAR_FORM_ERROR = `CLEAR_FORM_ERROR`;

